import { TagEntity } from '../../../../tags/infrastructure/persistence/relational/entities/tag.entity';

export const tagSeeds: TagEntity[] = [
  {
    id: 1,
    name: 'JavaScript',
    slug: 'javascript',
    description: 'JavaScript programming language',
    color: '#F7DF1E',
    isActive: true,
    usageCount: 0,
  } as TagEntity,
  {
    id: 2,
    name: 'TypeScript',
    slug: 'typescript',
    description: 'TypeScript programming language',
    color: '#3178C6',
    isActive: true,
    usageCount: 0,
  } as TagEntity,
  {
    id: 3,
    name: 'React',
    slug: 'react',
    description: 'React JavaScript library',
    color: '#61DAFB',
    isActive: true,
    usageCount: 0,
  } as TagEntity,
  {
    id: 4,
    name: 'Node.js',
    slug: 'nodejs',
    description: 'Node.js runtime environment',
    color: '#339933',
    isActive: true,
    usageCount: 0,
  } as TagEntity,
  {
    id: 5,
    name: 'NestJS',
    slug: 'nestjs',
    description: 'NestJS framework',
    color: '#E0234E',
    isActive: true,
    usageCount: 0,
  } as TagEntity,
  {
    id: 6,
    name: 'Python',
    slug: 'python',
    description: 'Python programming language',
    color: '#3776AB',
    isActive: true,
    usageCount: 0,
  } as TagEntity,
  {
    id: 7,
    name: 'Tutorial',
    slug: 'tutorial',
    description: 'Tutorial and learning content',
    color: '#FF6B6B',
    isActive: true,
    usageCount: 0,
  } as TagEntity,
  {
    id: 8,
    name: 'Best Practices',
    slug: 'best-practices',
    description: 'Best practices and guidelines',
    color: '#4ECDC4',
    isActive: true,
    usageCount: 0,
  } as TagEntity,
  {
    id: 9,
    name: 'API',
    slug: 'api',
    description: 'API development and design',
    color: '#45B7D1',
    isActive: true,
    usageCount: 0,
  } as TagEntity,
  {
    id: 10,
    name: 'Database',
    slug: 'database',
    description: 'Database design and optimization',
    color: '#96CEB4',
    isActive: true,
    usageCount: 0,
  } as TagEntity,
];
